version: "3"
services:
  tabbedcontent:
    image: splunk/splunk
    container_name: spl_tabbed_content
    ports:
      - "8000:8000"
      - "8089:8089"
    environment:
      OPTIMISTIC_ABOUT_FILE_LOCKING: '1'
      SPLUNK_START_ARGS: '--accept-license'
      SPLUNK_PASSWORD: "c3c76668-47be-42b7-9886-0201dcdb8e52"
    volumes:
      - ./simple_xml_tabs:/opt/splunk/etc/apps/simple_xml_tabs
    networks:
      splunk:
        aliases:
        - "splunksh"
  reactcontent:
    image: splunk/splunk
    container_name: spl_react_content
    ports:
      - "8000:8000"
      - "8089:8089"
    environment:
      OPTIMISTIC_ABOUT_FILE_LOCKING: '1'
      SPLUNK_START_ARGS: '--accept-license'
      SPLUNK_PASSWORD: "c3c76668-47be-42b7-9886-0201dcdb8e52"
    volumes:
      - ./simple_react_app:/opt/splunk/etc/apps/simple_react_app
    networks:
      splunk:
        aliases:
          - "splunksh"
networks:
  splunk:
